@startuml ER_SKUD

!include dist/common.puml
!include dist/v8_Document.puml
!include dist/v8_Catalog.puml
!include dist/v8_InfoRg.puml
!include dist/v8_Task.puml
!include dist/v8_BusinessProcess.puml
!include dist/v8_DataProcessor.puml

title 1С:Схема учета выдачи пропусков

caption Выдача пропусков

package ВыдачаПропусков <<Rectangle>> #ffff99 {

    v8_Catalog(Контрагенты)
    Контрагенты : Ссылка

    v8_Catalog(ФизическиеЛица, "Физические лица")
    ФизическиеЛица : Ссылка

    v8_Catalog(Организации, "Организации")
    Организации : Ссылка

    v8_Document(ЗаявкаНаВыдачуПропусков, "Заявка на выдачу пропусков")

    v8_Task(ЗадачаСогласованияВыдачиПропуска, "Задача согласования выдачи пропуска")

    v8_BusinessProcess(СогласованиеВыдачиПропуска, "Согласование выдачи пропуска")

    v8_InfoRg(РолиИсполнителей, "Роли исполнителей")

package ОбменССистемойСКУД <<Rectangle>> #b3c6ff {

    v8_Catalog(НастройкиПодключенияRabbit, "Настройки подключения Rabbit")
    НастройкиПодключенияRabbit : Ссылка
    
    v8_InfoRg(ОчередьВыгрузкиСообщений, "Очередь выгрузки сообщений")

    v8_DataProcessor("ОбменСКУД", "Обмен с системой СКУД")
}

Контрагенты-->ФизическиеЛица : Компания
ФизическиеЛица -->ЗаявкаНаВыдачуПропусков : Посетитель
Организации-->ЗаявкаНаВыдачуПропусков : Организация
ЗадачаСогласованияВыдачиПропуска-->СогласованиеВыдачиПропуска : Бизнес процесс
РолиИсполнителей -->СогласованиеВыдачиПропуска : Роль
ЗаявкаНаВыдачуПропусков-->СогласованиеВыдачиПропуска : Предмет
ЗаявкаНаВыдачуПропусков-->ОчередьВыгрузкиСообщений : Объект выгрузки
ОчередьВыгрузкиСообщений-->ОбменСКУД : Объекты выгрузки
НастройкиПодключенияRabbit-->ОбменСКУД : Настройки RMQ

@enduml